FROM bertoost/nginx
LABEL maintainer="Bert Oost <hello@bertoost.com>"

# Remove any parent placeholder files from NginX config
RUN find /etc/nginx/conf.d/ -name "*.placeholder" -type f -delete

COPY conf.d/dev/php.conf /etc/nginx/conf.d/default.placeholder

COPY conf.d/dev/postoffice.conf /etc/nginx/conf.d/a_postoffice.placeholder
COPY conf.d/dev/portainer.conf /etc/nginx/conf.d/a_portainer.placeholder